### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 5HT**

### CODE REVIEW

**Comment by 5HT** [comment]
I just want to notice that build has failed not because of this pull request :-)

**Comment by MasseR** [comment]
You might want to have a bit more descriptive commit message and/or describe the changes in a few werds in the PR description. If I was the reviewer, it would make me much more interested in reviewing the changes.

**Comment by 5HT** [comment]
Really? If you are unable to review 2 links you might want to remove my implementation of my recursion schemes from your fucking site :) You are not awesome.

**Comment by 5HT** [comment]
These guys don't deserve cubical rec schemes. Recursion schemes has zero application neither in math, nor in the academy. For the academy they are too simple, and for the programming they are too awkward. Jerking off rec schemes is not even start of the path.

**Comment by passy** [comment]
Christ, dude. Get a grip. You do realise what's going on in the world right now, don't you?

**Pull request closed without merging**
